# Generated by Django 5.2 on 2025-05-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
