# Generated by Django 5.2 on 2025-05-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_ride_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="end_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="end_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="start_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="start_lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
