# Generated by Django 5.2 on 2025-06-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ride_end_lat_ride_end_lng_ride_start_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('done', 'Done'), ('deleted', 'Deleted')], default='planned', max_length=20),
        ),
    ]
