# Generated by Django 5.2 on 2025-06-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_alter_ride_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='end_lng',
        ),
    ]
