# Generated by Django 5.2 on 2025-06-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_remove_ride_end_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='end_time',
        ),
        migrations.AddField(
            model_name='ride',
            name='end_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
